### PR TITLE
adding health

### PR DESCRIPTION
**Pull request by whitehawk0011**
I saw the documentation requirement for adding health.md in this repo https://github.com/adobe/aio-cli-health/issues/6 hence added the same

## Description

Adding the health.md from the repo https://github.com/adobe/aio-cli-health 

## Motivation and Context

Interested in this project and going through documentation, want to help and learn

This will add health to the documentation of the project

## How Has This Been Tested?

I have tested if it works properly using markdown editor

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.

### CODE REVIEW

**Comment by whitehawk0011** [comment]
ok , about the issues,
1. in which folder do I add health.xlsx?
2 .I understood, 

thanks for helping so much!

**Comment by shazron** [comment]
1. Same location as the health.md

**Comment by whitehawk0011** [comment]
done!

**Comment by whitehawk0011** [comment]
done & tested!

**Pull request merged**
