### PR TITLE
remove getting started

### PR DESCRIPTION
**Pull request by duynguyen**
Now our docs have a new home at https://github.com/AdobeDocs/project-firefly, no need to maintain the getting started in this readme anymore. Hence we remove it.

### CODE REVIEW

**Comment by shazron** [comment]
should we have a link pointing to the new docs?

**Comment by meryllblanchet** [comment]
@shazron yes, please. Great idea!

**Comment by shazron** [comment]
Instead of GH docs, I will use https://www.adobe.io/apis/experienceplatform/project-firefly.html

**Comment by duynguyen** [comment]
thanks @shazron , sorry I missed this thread earlier.

**Pull request merged**
