### PR TITLE
aio-next

### PR DESCRIPTION
**Pull request by purplecabbage**
## Description

The next version of the cli, a major update ( breaking change )
- use current versions of node ( 14, 16, 18 )
- use current oclif3 ( update tests, mocks, flags, requires to support it )
- rewrite some promise based tests to be clean awaitables

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by purplecabbage** [comment]
tests are failing because the plugins have incompatible peers as the updated versions are only pre-released.

**Comment by purplecabbage** [comment]
I removed reviewers hoping that I could make this a draft pr ... but I don't see the button
Consider this a draft until I get the telemetry to stop blocking CI

**Comment by MichaelGoberling** [comment]
Ran `aio info` and noticed a warning at the bottom about the current Node version not being supported, should this be updated?

```
  System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 295.95 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.5.0 - /usr/local/bin/npm
  Virtualization:
    Docker: 20.10.14 - /usr/local/bin/docker
  npmGlobalPackages:
    @adobe/aio-cli-next: 8.3.0-pre.2022-07-26.sha-8913399a

  Proxies:
    http: (not set)
    https: (not set)
  CLI plugins:
    core:
      @adobe/aio-cli-next 8.3.0-pre.2022-07-26.sha-8913399a
      @adobe/aio-cli-plugin-app 8.6.1-pre.2022-06-25.2ab6c018
      @adobe/aio-cli-plugin-auth 2.6.0-pre.2022-06-07.d66e9d3c
      @adobe/aio-cli-plugin-certificate 0.4.0
      @adobe/aio-cli-plugin-config 3.0.1-pre.2022-06-08.bd8bc4be
      @adobe/aio-cli-plugin-console 3.4.2-next.1
      @adobe/aio-cli-plugin-events 1.1.6-pre.2022-06-23.21ddad9a
      @adobe/aio-cli-plugin-info 2.1.0-pre.2022-06-08.cb620207
      @adobe/aio-cli-plugin-runtime 5.4.0-pre.2022-04-28.734a6d2c
      @adobe/aio-cli-plugin-telemetry 0.4.0-pre.2022-06-06.03a0a836
      @oclif/plugin-autocomplete 1.3.0
      @oclif/plugin-help 5.1.12
      @oclif/plugin-not-found 2.3.1
      @oclif/plugin-plugins 2.1.0
      @oclif/plugin-warn-if-update-available 2.0.4
    user:
    link:
 ›   Warning: Node version not supported. Supported versions are 10, 12, and 14      <-----
 ```

**Comment by shazron** [comment]
> Ran `aio info` and noticed a warning at the bottom about the current Node version not being supported, should this be updated?

Yup. https://github.com/adobe/aio-cli-plugin-info/blob/cb620207d70485cc9e5784d66708c77093d78467/src/commands/info.js#L122 looks like we hard-code this

**Pull request merged**
