### PR TITLE
Update readme with getting started guidance

### PR DESCRIPTION
**Pull request by duynguyen**
The new readme mainly shows a "getting started" with Adobe I/O App. All detailed commands to to a separate file.

## Motivation and Context

The full list of commands is useful for reference purpose. However when the CLI users firstly try out the CLI, we should show them the (guided) basic flow of using the tool.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by purplecabbage** [comment]
README includes sections that are auto generated when apis change, this is all broken now.
Instruction say you need to install wskdebug, however this is a project level dependency and a global install is not required.

**Comment by duynguyen** [comment]
@purplecabbage, I have moved the generated sections to COMMANDS.md, is it possible to make the auto-generating script printing its results to that fine instead of README.md?

**Comment by duynguyen** [comment]
ok as oclif adds the generated commands section directly to readme (and hardcoded), I added it back. As an alternative, the new "getting started" section is placed on top.

**Comment by shazron** [comment]
Sorry Duy I tried to find if there was the option to use a different filename -- it's hardcoded here https://github.com/oclif/dev-cli/blob/1ea7b27bb9eda6eb38dcd60e6c7a44df7c72b28b/src/commands/readme.ts#L43

**Comment by duynguyen** [comment]
@shazron thanks for checking, yeah it looks like not possible.
Is it fine what I am doing? (placing the custom content before the generated content)

**Pull request merged**
