### PR TITLE
v2.3.0

### PR DESCRIPTION
**Pull request by purplecabbage**
## Description

Release v2.3.0 

## Motivation and Context

It's time

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by purplecabbage** [comment]
Need to get the latest runtime plugin changes in here as well.

**Comment by shazron** [comment]
We need to update the health matrix as well.

**Comment by shazron** [comment]
Auth plugin inclusion as well (merge from master)

**Comment by shazron** [comment]
@purplecabbage 2.3.0 seems to be already published? close this?

**Pull request merged**
